CREATE TABLE trunk (
  id INTEGER NOT NULL PRIMARY KEY,
  card_id TEXT NOT NULL UNIQUE,
  amount INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (card_id) REFERENCES card (card_id) ON DELETE CASCADE ON UPDATE CASCADE
);
