packages:
  - "app"

dedupePeers: true
ignoreWorkspaceRootCheck: true
trustPolicy: no-downgrade

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@tb-dev/*"
  - "@tsukilabs/*"

allowBuilds:
  vue-demi: false

overrides:
  flatted@<=3.4.1: ">=3.4.2"
  yaml@>=2.0.0 <2.8.3: ">=2.8.3"
