[package]
name = "deckbox"
publish = false

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
deckbox-database.workspace = true
futures.workspace = true
itertools.workspace = true
jiff.workspace = true
nil-log.workspace = true
mimalloc.workspace = true
open.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tap.workspace = true
tauri-plugin-clipboard-manager.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-fs.workspace = true
tauri-plugin-opener.workspace = true
tauri-plugin-os.workspace = true
tauri-plugin-persisted-scope.workspace = true
tauri-plugin-pinia.workspace = true
tauri-plugin-prevent-default.workspace = true
tauri-plugin-process.workspace = true
tauri-plugin-single-instance.workspace = true
tauri-plugin-updater.workspace = true
tauri-specta.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
ygo.workspace = true

[dependencies.tauri]
version = "2.11"
features = ["protocol-asset", "rustls-tls"]

[build-dependencies.tauri-build]
version = "2.6"
features = []
