// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async showWindow() : Promise<null> {
    return await TAURI_INVOKE("show_window");
},
async fetchCards() : Promise<null> {
    return await TAURI_INVOKE("fetch_cards");
},
async getArchetypes() : Promise<string[]> {
    return await TAURI_INVOKE("get_archetypes");
},
async getCardByCardId(cardId: Db_CardId) : Promise<Db_Card> {
    return await TAURI_INVOKE("get_card_by_card_id", { cardId });
},
async getCards() : Promise<Db_Card[]> {
    return await TAURI_INVOKE("get_cards");
},
async createTrunkEntry(cardId: Db_CardId) : Promise<number> {
    return await TAURI_INVOKE("create_trunk_entry", { cardId });
},
async decreaseTrunkEntryAmount(cardId: Db_CardId) : Promise<number> {
    return await TAURI_INVOKE("decrease_trunk_entry_amount", { cardId });
},
async getTrunk() : Promise<Db_TrunkEntry[]> {
    return await TAURI_INVOKE("get_trunk");
},
async getTrunkEntryByCardId(cardId: Db_CardId) : Promise<Db_TrunkEntry> {
    return await TAURI_INVOKE("get_trunk_entry_by_card_id", { cardId });
},
async hasTrunkEntry(cardId: Db_CardId) : Promise<boolean> {
    return await TAURI_INVOKE("has_trunk_entry", { cardId });
},
async increaseTrunkEntryAmount(cardId: Db_CardId) : Promise<Db_TrunkEntryAmount> {
    return await TAURI_INVOKE("increase_trunk_entry_amount", { cardId });
},
async createWish(cardId: Db_CardId) : Promise<number> {
    return await TAURI_INVOKE("create_wish", { cardId });
},
async getWishByCardId(cardId: Db_CardId) : Promise<Db_Wish> {
    return await TAURI_INVOKE("get_wish_by_card_id", { cardId });
},
async getWishlist() : Promise<Db_Wish[]> {
    return await TAURI_INVOKE("get_wishlist");
},
async removeWish(cardId: Db_CardId) : Promise<number> {
    return await TAURI_INVOKE("remove_wish", { cardId });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BanlistStatus = "Forbidden" | "Limited" | "Semi-Limited"
export type CardAttribute = "DARK" | "DIVINE" | "EARTH" | "FIRE" | "LIGHT" | "WATER" | "WIND"
export type CardRace = "Abidos the Th" | "Adrian Gecko" | "Alexis Rhodes" | "Amnael" | "Andrew" | "Aqua" | "Arkana" | "Aster Phoenix" | "Axel Brodie" | "Bastion Misaw" | "Beast" | "Beast-Warrior" | "Bonz" | "Camula" | "Chazz Princet" | "Christine" | "Chumley Huffi" | "Continuous" | "Counter" | "Creator God" | "Cyberse" | "David" | "Dinosaur" | "Divine-Beast" | "Don Zaloog" | "Dragon" | "Dr. Vellian C" | "Emma" | "Equip" | "Espa Roba" | "Fairy" | "Field" | "Fiend" | "Fish" | "Illusion" | "Insect" | "Ishizu" | "Ishizu Ishtar" | "Jaden Yuki" | "Jesse Anderso" | "Joey" | "Joey Wheeler" | "Kagemaru" | "Kaiba" | "Keith" | "Lumis and Umb" | "Lumis Umbra" | "Machine" | "Mai" | "Mai Valentine" | "Mako" | "Nightshroud" | "" | "Normal" | "Odion" | "Paradox Broth" | "Pegasus" | "Plant" | "Psychic" | "Pyro" | "Quick-Play" | "Reptile" | "Rex" | "Ritual" | "Rock" | "Sea Serpent" | "Seto Kaiba" | "Spellcaster" | "Syrus Truesda" | "Tania" | "Tea Gardner" | "Thelonious Vi" | "The Supreme K" | "Thunder" | "Titan" | "Tyranno Hassl" | "Warrior" | "Weevil" | "Winged Beast" | "Wyrm" | "Yami Bakura" | "Yami Marik" | "Yami Yugi" | "Yubel" | "Yugi" | "Zane Truesdal" | "Zombie"
export type CardType = "Effect Monster" | "Flip Effect Monster" | "Flip Tuner Effect Monster" | "Fusion Monster" | "Gemini Monster" | "Link Monster" | "Normal Monster" | "Normal Tuner Monster" | "Pendulum Effect Fusion Monster" | "Pendulum Effect Monster" | "Pendulum Effect Ritual Monster" | "Pendulum Flip Effect Monster" | "Pendulum Normal Monster" | "Pendulum Tuner Effect Monster" | "Ritual Effect Monster" | "Ritual Monster" | "Skill Card" | "Spell Card" | "Spirit Monster" | "Synchro Monster" | "Synchro Pendulum Effect Monster" | "Synchro Tuner Monster" | "Token" | "Toon Monster" | "Trap Card" | "Tuner Monster" | "Union Effect Monster" | "XYZ Monster" | "XYZ Pendulum Effect Monster"
export type Db_BanlistStatus = BanlistStatus
export type Db_Card = { name: string; description: string; cardId: Db_CardId; cardType: Db_CardType; cardTypeHuman: string | null; cardRace: Db_CardRace; attack: number | null; defense: number | null; level: number | null; linkval: number | null; attribute: Db_CardAttribute | null; archetype: string | null; banlistStatus: Db_BanlistStatus | null; imageUrl: Db_Url; imageUrlCropped: Db_Url; imageUrlSmall: Db_Url; price: string | null }
export type Db_CardAttribute = CardAttribute
export type Db_CardId = string
export type Db_CardRace = CardRace
export type Db_CardType = CardType
export type Db_TrunkEntry = { cardId: Db_CardId; amount: Db_TrunkEntryAmount }
export type Db_TrunkEntryAmount = number
export type Db_Url = string
export type Db_Wish = { cardId: Db_CardId }
export type Error = string

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
